### ISSUE TITLE
[PE-D][Tester E] Datetime Expiring

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-4/tp#137]
Did a good job checking for interview datetime to be older than the application datetime. A suggestion would be that if the datetime expires (maybe after a given period), the status should change to make it more intuitive for the user.

As shown in the screenshot, the interview datetime is 31-03-2023 14:35 but the current datetime is already 31-03-2023 14:36.

![image.png](https://raw.githubusercontent.com/pzaiming/ped/main/files/17ac3c0e-bbf1-4666-b499-cf4dfc7ef7b5.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: pzaiming/ped#3

**Comment by FredericChow00** [comment]
Mentioned this in Planned Enhancement section of DG
