### ISSUE TITLE
[PE-D][Tester A] unexpected date inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-4/tp#140]
![Screenshot 2023-03-31 at 2.34.08 PM.png](https://raw.githubusercontent.com/NappySprout/ped/main/files/12866c0b-7aaf-49d8-9899-cedf0cefaedd.png)

inputting 31-02-2024 for interview date does not give me an error, but the program just silently set it as 29-02-2024. 

Discrepancy with what is input as compared to what is stored might confuse users.

 Program should simply throw an error for an invalidate date like 31-02-2024

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: NappySprout/ped#2

**Comment by FredericChow00** [comment]
Mentioned this in Planned Enhancement section of DG
