### ISSUE TITLE
[PE-D][Tester E] Application Datetime is Missing in the UI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-4/tp#151]
Good job keep track of the application deadline of the applicants which can be useful information!

I am not sure if the team wanted to show the application deadline on the addressbook as this detail can only be seen from using certain commands such as `edit`. If the application datetime is meant to hidden, it should not be revealed at the edit command too as shown in the screenshot. 

![image.png](https://raw.githubusercontent.com/pzaiming/ped/main/files/de0856bd-0302-493f-a126-25fdba3cd561.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: pzaiming/ped#7

**Comment by FredericChow00** [comment]
Mentioned this in Planned Enhancement section of DG
