### ISSUE TITLE
[PE-D][Tester E] Phone Number as an Attribute for Uniqueness

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-4/tp#154]
Good job on preventing the addition of duplicates!

UG mentioned the uniqueness is done through checking name and phone number. However I feel that the phone number should be unique as two different person should not have the same phone number. 

![image.png](https://raw.githubusercontent.com/pzaiming/ped/main/files/9727b06e-3c0a-465c-8dc7-0cb236163622.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: pzaiming/ped#8

**Comment by FredericChow00** [comment]
Mentioned this in Planned Enhancement section of DG
